name: Build and deploy ASP.Net Core app to Azure Web App - AwesomeLibrary-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 🔥 Node för Angular
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 🔥 Bygg Angular
      - name: Build Angular
        run: |
          cd Frontend
          npm install
          npm run build

      # 🔥 Kopiera till backend
      - name: Copy Angular to wwwroot
        run: |
          mkdir Backend/LibraryApp.Api/wwwroot
          xcopy Frontend\dist\browser\* Backend\LibraryApp.Api\wwwroot\ /E /I

      # 🔥 .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # 🔥 FIX: rätt path
      - name: Build with dotnet
        run: dotnet build Backend/LibraryApp.Api/LibraryApp.Api.csproj --configuration Release

      # 🔥 FIX: rätt path
      - name: dotnet publish
        run: dotnet publish Backend/LibraryApp.Api/LibraryApp.Api.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BC956FBF8DC143C8AE58078FF399EEB6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61A84DDD2F6F415C8FF6265DD8EA57AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7590C5A49FDA47078ED6F64B7398BF8D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AwesomeLibrary-backend'
          slot-name: 'Production'
          package: .
